### PR TITLE
Add auto-rendered product layout

### LINKED ISSUE #110: Add auto-rendered product layout
Add auto-rendered product layout where the product data is rendered based on [product drop](https://www.voog.com/developers/markup/ecommerce-objects/product) data.

It should look like current "Product" layout. Use new [image](https://www.voog.com/developers/markup/tags/image) or [image_data](https://www.voog.com/developers/markup/tags/image-data) tag for product cover image.

It content type must be `product`:

```json
{
  "content_type": "product",
  "component": false,
  "file": "layouts/auto_generated_product.tpl",
  "layout_name": "auto_generated_product",
  "title": "Auto-generated product"
}
```

See also buy button rendering example in [Nuuk design](https://github.com/Voog/design-nuuk/blob/master/components/buy-button.tpl).

## TODO

* [ ] Add "Auto-generated product" layout
* [ ] Check and improve "[product list](https://www.voog.com/support/online-store/product-list-content-area)" widget styles when needed.

### PR DESCRIPTION
**Pull request by PeeterPaal**
Adds auto-rendered product layout.
Also adds a browser hack to enhance image rendering in Chrome based browsers.
Closes #110

### CODE REVIEW

**Review by tanelj — CHANGES_REQUESTED** [review]
Nice! Only minor issue with forms:

* [x] When form is inside content area then layout is not correct:
Screenshot 2022-02-07 at 16 34 49

**Review by pxska — APPROVED** [review]
Looks good!

**Review by tanelj — APPROVED** [review]
Nice work.

**Review by tanelj — CHANGES_REQUESTED** [review]
Nice work, and works as expected but here are now some broken issues:

* [x] `BgPicker's `el` parameter has to be either a plain DOM node or a jQuery object around a DOM node.` since on the page has no BG pickers. One example source of the errro: https://github.com/Voog/design-dusseldorf/blob/3e00e023b68edd8a13e981577201bdb20273a6b1/components/edicy-tools.tpl#L65 . NB `Edicy.BgPicker()` first parameter (selector target)must be present in page!
* [x] When you try rezize window then JS error `Uncaught TypeError: e is undefined` occurs. https://github.com/Voog/design-dusseldorf/blob/e0ca47b23679ad4daaf70f2bfe128e3a6f1fb9c6/sources/javascripts/concat/editmode/editmode.js#L4  its `debounce` first parameter `func` that is missing (undefined). Maybe called here: https://github.com/Voog/design-dusseldorf/blob/e0ca47b23679ad4daaf70f2bfe128e3a6f1fb9c6/sources/javascripts/concat/editmode/editmode.js#L99 (should `setTitlebox;` to be `setTitlebox();`?

**Review by tanelj — APPROVED** [review]

**Review by pxska — APPROVED** [review]

**Pull request merged**
